#!/usr/bin/env bash
# This script stops 4-to_infinity_and_beyond without using kill or killall

# shellcheck disable=SC2009
pid=$(ps -ef | grep "[4]-to_infinity_and_beyond" | awk '{print $2}')

if [ -n "$pid" ]; then
    echo 1000 > "/proc/$pid/oom_score_adj" 
    
else
    echo "Process not found."
fi
